# Generated by Django 4.1.7 on 2023-03-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0002_transactioncategory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fi.transactioncategory'),
        ),
    ]
