# Generated by Django 4.1.7 on 2023-04-29 10:04

import datetime
from django.db import migrations, models
import fi.models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0003_alter_transactioncategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 29)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], default='E', max_length=1, validators=[fi.models.transaction_type_validate]),
        ),
    ]
