# Generated by Django 4.1.7 on 2023-04-29 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0004_alter_transaction_date_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 29, 12, 56, 47, 274494, tzinfo=datetime.timezone.utc)),
        ),
    ]
